apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol
  namespace: default
spec:
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

