apiVersion: v1
kind: Service
metadata:
  name: netology-web
spec:
  selector:
    app: netology-web
  ports:
    - name: netology-web
      protocol: TCP
      port: 80
      targetPort: 8080
      
    