apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multitool
  name: pod-multitool
  namespace: default
spec:
  containers:
  - image: wbitt/network-multitool
    imagePullPolicy: IfNotPresent
    name: multitool
    