apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-check-svc
  labels:
    app: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: 
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 80
      initContainers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'until nslookup netology-nginx.default.svc.cluster.local; do echo waiting for netology-nginx; sleep 5; done;']
