apiVersion: v1
kind: Service
metadata:
  name: netology-nginx
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: multitool
      protocol: TCP
      port: 8090
      targetPort: 8080

    