---
namespace: default
frontend:
  replicaCount: 3
  image: nginx:1.22
  containerPort: 80

backend:
  replicaCount: 1
  image: wbitt/network-multitool
  containerPort: 8080

servicefrontend:
  port: 80
servicebackend:
  port: 8080
---
