apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-multitool
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-multitool
  ports:
    - name: multitool
      protocol: TCP
      port: {{ .Values.servicebackend.port }}

  
    