---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-canary2
  labels:
    app: {{ .Release.Name }}-nginx2
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.canary.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx2
  template:
    metadata:
      labels: 
        app: {{ .Release.Name }}-nginx2
    spec:
      containers:
      - name: nginx2
        image: {{ .Values.canary.image }}
        ports:
          - containerPort: {{ .Values.canary.containerPort }}
        volumeMounts:
          - name: {{ .Release.Name }}-web2
            mountPath: /usr/share/nginx/html
      volumes:
        - name: {{ .Release.Name }}-web2
          configMap:
            name: {{ .Release.Name }}-nginx2
---
