---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-canary1
  labels:
    app: {{ .Release.Name }}-nginx1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.canary.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx1
  template:
    metadata:
      labels: 
        app: {{ .Release.Name }}-nginx1
    spec:
      containers:
      - name: nginx1
        image: {{ .Values.canary.image }}
        ports:
          - containerPort: {{ .Values.canary.containerPort }}
        volumeMounts:
        - name: {{ .Release.Name }}-web1
          mountPath: /usr/share/nginx/html
      volumes:
        - name: {{ .Release.Name }}-web1
          configMap:
            name: {{ .Release.Name }}-nginx1
---
