apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: netotest.local
    http:
      paths:
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-nginx1
            port:
              number: 80
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-nginx2
            port:
              number: 80


