apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx2
spec:
  selector:
    app: {{ .Release.Name }}-nginx2
  ports:
    - name: {{ .Release.Name }}-nginx2
      protocol: TCP
      port: 80

  
    