kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  cluster_type: "kubespray"
  calico_backend: "vxlan"
# The CNI network configuration to install on each node. The special
  # values in this config will be automatically populated.
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion":"0.3.1",
      "plugins":[
        {
                      "datastore_type": "kubernetes",
            "nodename": "__KUBERNETES_NODE_NAME__",
                      "type": "calico",
            "log_level": "info",
                      "log_file_path": "/var/log/calico/cni/cni.log",
                                          "ipam": {
              "type": "calico-ipam",
                          "assign_ipv4": "true"
                                    },
                                                    "policy": {
              "type": "k8s"
            },
                                "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
            }
        },
        {
          "type":"portmap",
          "capabilities": {
            "portMappings": true
          }
        },
        {
          "type":"bandwidth",
          "capabilities": {
            "bandwidth": true
          }
        }
      ]
    }
