apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "192.168.0.135"
  bindPort: 6443
certificateKey: cd0e6ff41de7ab1ff154dc3ccff9bf6faad42dad2deacc100fa68a2a0255ba0a
nodeRegistration:
  name: "node1"
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
clusterName: cluster.local
encryptionAlgorithm: RSA-2048
certificateValidityPeriod: 8760h
caCertificateValidityPeriod: 87600h
etcd:
  external:
      endpoints:
      - "https://192.168.0.135:2379"
      - "https://192.168.0.141:2379"
      - "https://192.168.0.142:2379"
      caFile: /etc/ssl/etcd/ssl/ca.pem
      certFile: /etc/ssl/etcd/ssl/node-node1.pem
      keyFile: /etc/ssl/etcd/ssl/node-node1-key.pem
dns:
  disabled: true
  imageRepository: registry.k8s.io/coredns
  imageTag: v1.12.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: "10.233.0.0/18"
  podSubnet: "10.233.64.0/18"
kubernetesVersion: v1.33.1
controlPlaneEndpoint: "192.168.0.50:6443"
certificatesDir: /etc/kubernetes/ssl
imageRepository: registry.k8s.io
apiServer:
  extraArgs:
  - name: etcd-compaction-interval
    value: "5m0s"
  - name: default-not-ready-toleration-seconds
    value: "300"
  - name: default-unreachable-toleration-seconds
    value: "300"
  - name: anonymous-auth
    value: "True"
  - name: authorization-mode
    value: "Node,RBAC"
  - name: bind-address
    value: "::"
  - name: apiserver-count
    value: "3"
  - name: endpoint-reconciler-type
    value: lease
  - name: service-node-port-range
    value: "30000-32767"
  - name: service-cluster-ip-range
    value: "10.233.0.0/18"
  - name: kubelet-preferred-address-types
    value: "InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP"
  - name: profiling
    value: "False"
  - name: request-timeout
    value: "1m0s"
  - name: enable-aggregator-routing
    value: "False"
  - name: service-account-lookup
    value: "True"
  - name: storage-backend
    value: "etcd3"
  - name: allow-privileged
    value: "true"
  - name: event-ttl
    value: "1h0m0s"
  extraVolumes:
  - name: usr-share-ca-certificates
    hostPath: /usr/share/ca-certificates
    mountPath: /usr/share/ca-certificates
    readOnly: true
  certSANs:
  - "kubernetes"
  - "kubernetes.default"
  - "kubernetes.default.svc"
  - "kubernetes.default.svc.cluster.local"
  - "10.233.0.1"
  - "localhost"
  - "127.0.0.1"
  - "::1"
  - "node1"
  - "node2"
  - "node3"
  - "lb-apiserver.kubernetes.local"
  - "192.168.0.50"
  - "192.168.0.135"
  - "192.168.0.141"
  - "192.168.0.142"
  - "node1.cluster.local"
  - "node2.cluster.local"
  - "node3.cluster.local"
controllerManager:
  extraArgs:
  - name: node-monitor-grace-period
    value: "40s"
  - name: node-monitor-period
    value: "5s"
  - name: cluster-cidr
    value: "10.233.64.0/18"
  - name: service-cluster-ip-range
    value: "10.233.0.0/18"
  - name: allocate-node-cidrs
    value: "false"
  - name: profiling
    value: "False"
  - name: terminated-pod-gc-threshold
    value: "12500"
  - name: bind-address
    value: "::"
  - name: leader-elect-lease-duration
    value: "15s"
  - name: leader-elect-renew-deadline
    value: "10s"
  - name: configure-cloud-routes
    value: "false"
scheduler:
  extraArgs:
  - name: bind-address
    value: "::"
  - name: config
    value: "/etc/kubernetes/kubescheduler-config.yaml"
  - name: profiling
    value: "False"
  extraVolumes:
  - name: kubescheduler-config
    hostPath: /etc/kubernetes/kubescheduler-config.yaml
    mountPath: /etc/kubernetes/kubescheduler-config.yaml
    readOnly: true
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: UpgradeConfiguration
apply:
  kubernetesVersion: v1.33.1
  allowExperimentalUpgrades: true
  certificateRenewal: true
  etcdUpgrade: false
  forceUpgrade: true
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
node:
  certificateRenewal: true
  etcdUpgrade: false
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: "0.0.0.0"
clientConnection:
  acceptContentTypes: 
  burst: 10
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: 
  qps: 5
clusterCIDR: "10.233.64.0/18"
configSyncPeriod: 15m0s
conntrack:
  maxPerCore: 32768
  min: 131072
  tcpCloseWaitTimeout: 1h0m0s
  tcpEstablishedTimeout: 24h0m0s
enableProfiling: False
healthzBindAddress: "0.0.0.0:10256"
hostnameOverride: "node1"
iptables:
  masqueradeAll: False
  masqueradeBit: 14
  minSyncPeriod: 0s
  syncPeriod: 30s
ipvs:
  excludeCIDRs: []
  minSyncPeriod: 0s
  scheduler: rr
  syncPeriod: 30s
  strictARP: False
  tcpTimeout: 0s
  tcpFinTimeout: 0s
  udpTimeout: 0s
metricsBindAddress: "127.0.0.1:10249"
mode: ipvs
nodePortAddresses: []
oomScoreAdj: -999
portRange: 
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:
- 169.254.25.10
