apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool-deployment
  labels:
    app: nginx-mtool
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-mtool
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: nginx-mtool
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
          - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        ports:
          - containerPort: 8080
        env:
          - name: HTTP_PORT
            value: "8080"

        

